## Tensor
Numpy ndarray와 유사, Pytorch 모델의 기본 입력/출력/파라미터 자료형, gpu 가속 & 자동미분이 편리함

In [84]:
import torch
import numpy as np

#### Define Tensor

In [85]:
li = [[1,2],[3,4]]
t = torch.tensor(li)
t

tensor([[1, 2],
        [3, 4]])

In [86]:
arr = np.array(li)
t = torch.tensor(arr)
t

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [87]:
t1 = torch.ones_like(t)
tr = torch.rand_like(t, dtype = torch.float) #rand_like는 float 자료형만 됨
t1, tr

(tensor([[1, 1],
         [1, 1]], dtype=torch.int32),
 tensor([[0.5600, 0.6551],
         [0.9150, 0.5201]]))

In [88]:
t0 = torch.zeros((2,2))
t1 = torch.ones((2,2))
tr = torch.rand((2,2))
t0,t1,tr

(tensor([[0., 0.],
         [0., 0.]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[0.0958, 0.9497],
         [0.3824, 0.4041]]))

#### Attributes of Tensor

In [89]:
t.shape, t.dtype, t.device

(torch.Size([2, 2]), torch.int32, device(type='cpu'))

#### Operations on Tensor

Numpy 연산이랑 유사하다. Broadcasting 등등 다 된다.

In [90]:
t1 = torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])
t2 = torch.ones_like(t1)
t1, t2

(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 tensor([[[1, 1],
          [1, 1]],
 
         [[1, 1],
          [1, 1]]]))

In [91]:
t1[0], t1[:,0], t1[...,0], t1[0,...,0]

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1, 2],
         [5, 6]]),
 tensor([[1, 3],
         [5, 7]]),
 tensor([1, 3]))

In [92]:
tc,tc1,tc2,tc3 = torch.cat([t1,t2]), torch.cat([t1,t2],dim = 0), torch.cat([t1,t2],dim = 1), torch.cat([t1,t2], dim = 2)

In [93]:
tc.shape, tc1.shape, tc2.shape, tc3.shape

(torch.Size([4, 2, 2]),
 torch.Size([4, 2, 2]),
 torch.Size([2, 4, 2]),
 torch.Size([2, 2, 4]))

In [94]:
t, t.T

(tensor([[1, 2],
         [3, 4]], dtype=torch.int32),
 tensor([[1, 3],
         [2, 4]], dtype=torch.int32))

In [95]:
t+t.T, t-t.T, t*t.T, t@t.T

(tensor([[2, 5],
         [5, 8]], dtype=torch.int32),
 tensor([[ 0, -1],
         [ 1,  0]], dtype=torch.int32),
 tensor([[ 1,  6],
         [ 6, 16]], dtype=torch.int32),
 tensor([[ 5, 11],
         [11, 25]], dtype=torch.int32))

In [96]:
t0 = torch.tensor([[[100]]])
t0.shape, t0.item()

(torch.Size([1, 1, 1]), 100)

#### Numpy Array and Tensor

In [97]:
nt = np.array([[1,2],[3,4]])
tn = torch.from_numpy(nt) #same memory
tn2 = torch.tensor(nt) #different memory
nt,tn,tn2

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]], dtype=torch.int32),
 tensor([[1, 2],
         [3, 4]], dtype=torch.int32))

In [98]:
np.add(nt, 1, out = nt)
nt, tn, tn2

(array([[2, 3],
        [4, 5]]),
 tensor([[2, 3],
         [4, 5]], dtype=torch.int32),
 tensor([[1, 2],
         [3, 4]], dtype=torch.int32))